import {
    defineConfig
}
from "vitepress";

export default defineConfig({
    lang: "zh-CN",
    title: "Holy Bible",
    description: "the Holy Bible for Web",
    head: [
        ["link", {
            rel: "preconnect",
            href: "https://unpkg.com"
        }],
        ["link", {
            rel: "dns-prefetch",
            href: "https://unpkg.com"
        }],
        ["script", {
            src: "https://unpkg.com/twemoji@latest/dist/twemoji.min.js"
        }], ],
    lastUpdated: true,
    markdown: {
        theme: "one-dark-pro",
        lineNumbers: true,
    },
    themeConfig: {
        logo: "",
        nav: [{
            text: "文档",
            link: "/intro"
        }, {
            text: "找我",
            items: [{
                items: [{
                    text: "GitHub",
                    link: "https://github.com/Lisk809"
                }, {
                    text: "QQ",
                    link: "https://qm.qq.com/cgi-bin/qm/qr?k=z_MhzXU1RM0HEnIOBmXiERGNuDxpHglV&noverify=0",
                }, ],
            }, ],
        }, ],
        sidebar: [{
            text: "开始",
            collapsible: true,
            items: [{
                text: "简介",
                link: "/intro"
            }],
        }, {
            text: "bible",
            collapsible: true,
            items: [{
                "text": "以弗所书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/以弗所书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/以弗所书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/以弗所书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/以弗所书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/以弗所书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/以弗所书/6.md"
                }]
            }, {
                "text": "使徒行传",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/使徒行传/1.md"
                }, {
                    "text": "第10章",
                    "link": "/使徒行传/10.md"
                }, {
                    "text": "第11章",
                    "link": "/使徒行传/11.md"
                }, {
                    "text": "第12章",
                    "link": "/使徒行传/12.md"
                }, {
                    "text": "第13章",
                    "link": "/使徒行传/13.md"
                }, {
                    "text": "第14章",
                    "link": "/使徒行传/14.md"
                }, {
                    "text": "第15章",
                    "link": "/使徒行传/15.md"
                }, {
                    "text": "第16章",
                    "link": "/使徒行传/16.md"
                }, {
                    "text": "第17章",
                    "link": "/使徒行传/17.md"
                }, {
                    "text": "第18章",
                    "link": "/使徒行传/18.md"
                }, {
                    "text": "第19章",
                    "link": "/使徒行传/19.md"
                }, {
                    "text": "第2章",
                    "link": "/使徒行传/2.md"
                }, {
                    "text": "第20章",
                    "link": "/使徒行传/20.md"
                }, {
                    "text": "第21章",
                    "link": "/使徒行传/21.md"
                }, {
                    "text": "第22章",
                    "link": "/使徒行传/22.md"
                }, {
                    "text": "第23章",
                    "link": "/使徒行传/23.md"
                }, {
                    "text": "第24章",
                    "link": "/使徒行传/24.md"
                }, {
                    "text": "第25章",
                    "link": "/使徒行传/25.md"
                }, {
                    "text": "第26章",
                    "link": "/使徒行传/26.md"
                }, {
                    "text": "第27章",
                    "link": "/使徒行传/27.md"
                }, {
                    "text": "第28章",
                    "link": "/使徒行传/28.md"
                }, {
                    "text": "第3章",
                    "link": "/使徒行传/3.md"
                }, {
                    "text": "第4章",
                    "link": "/使徒行传/4.md"
                }, {
                    "text": "第5章",
                    "link": "/使徒行传/5.md"
                }, {
                    "text": "第6章",
                    "link": "/使徒行传/6.md"
                }, {
                    "text": "第7章",
                    "link": "/使徒行传/7.md"
                }, {
                    "text": "第8章",
                    "link": "/使徒行传/8.md"
                }, {
                    "text": "第9章",
                    "link": "/使徒行传/9.md"
                }]
            }, {
                "text": "加拉太书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/加拉太书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/加拉太书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/加拉太书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/加拉太书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/加拉太书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/加拉太书/6.md"
                }]
            }, {
                "text": "启示录",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/启示录/1.md"
                }, {
                    "text": "第10章",
                    "link": "/启示录/10.md"
                }, {
                    "text": "第11章",
                    "link": "/启示录/11.md"
                }, {
                    "text": "第12章",
                    "link": "/启示录/12.md"
                }, {
                    "text": "第13章",
                    "link": "/启示录/13.md"
                }, {
                    "text": "第14章",
                    "link": "/启示录/14.md"
                }, {
                    "text": "第15章",
                    "link": "/启示录/15.md"
                }, {
                    "text": "第16章",
                    "link": "/启示录/16.md"
                }, {
                    "text": "第17章",
                    "link": "/启示录/17.md"
                }, {
                    "text": "第18章",
                    "link": "/启示录/18.md"
                }, {
                    "text": "第19章",
                    "link": "/启示录/19.md"
                }, {
                    "text": "第2章",
                    "link": "/启示录/2.md"
                }, {
                    "text": "第20章",
                    "link": "/启示录/20.md"
                }, {
                    "text": "第21章",
                    "link": "/启示录/21.md"
                }, {
                    "text": "第22章",
                    "link": "/启示录/22.md"
                }, {
                    "text": "第3章",
                    "link": "/启示录/3.md"
                }, {
                    "text": "第4章",
                    "link": "/启示录/4.md"
                }, {
                    "text": "第5章",
                    "link": "/启示录/5.md"
                }, {
                    "text": "第6章",
                    "link": "/启示录/6.md"
                }, {
                    "text": "第7章",
                    "link": "/启示录/7.md"
                }, {
                    "text": "第8章",
                    "link": "/启示录/8.md"
                }, {
                    "text": "第9章",
                    "link": "/启示录/9.md"
                }]
            }, {
                "text": "哥林多前书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/哥林多前书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/哥林多前书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/哥林多前书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/哥林多前书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/哥林多前书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/哥林多前书/14.md"
                }, {
                    "text": "第15章",
                    "link": "/哥林多前书/15.md"
                }, {
                    "text": "第16章",
                    "link": "/哥林多前书/16.md"
                }, {
                    "text": "第2章",
                    "link": "/哥林多前书/2.md"
                }, {
                    "text": "第4章",
                    "link": "/哥林多前书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/哥林多前书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/哥林多前书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/哥林多前书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/哥林多前书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/哥林多前书/9.md"
                }]
            }, {
                "text": "哥林多后书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/哥林多后书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/哥林多后书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/哥林多后书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/哥林多后书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/哥林多后书/13.md"
                }, {
                    "text": "第2章",
                    "link": "/哥林多后书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/哥林多后书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/哥林多后书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/哥林多后书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/哥林多后书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/哥林多后书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/哥林多后书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/哥林多后书/9.md"
                }]
            }, {
                "text": "希伯来书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/希伯来书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/希伯来书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/希伯来书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/希伯来书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/希伯来书/13.md"
                }, {
                    "text": "第2章",
                    "link": "/希伯来书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/希伯来书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/希伯来书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/希伯来书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/希伯来书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/希伯来书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/希伯来书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/希伯来书/9.md"
                }]
            }, {
                "text": "帖撒罗尼迦前书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/帖撒罗尼迦前书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/帖撒罗尼迦前书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/帖撒罗尼迦前书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/帖撒罗尼迦前书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/帖撒罗尼迦前书/5.md"
                }]
            }, {
                "text": "帖撒罗尼迦后书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/帖撒罗尼迦后书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/帖撒罗尼迦后书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/帖撒罗尼迦后书/3.md"
                }]
            }, {
                "text": "彼得前书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/彼得前书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/彼得前书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/彼得前书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/彼得前书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/彼得前书/5.md"
                }]
            }, {
                "text": "彼得后书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/彼得后书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/彼得后书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/彼得后书/3.md"
                }]
            }, {
                "text": "提多书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/提多书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/提多书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/提多书/3.md"
                }]
            }, {
                "text": "提摩太前书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/提摩太前书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/提摩太前书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/提摩太前书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/提摩太前书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/提摩太前书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/提摩太前书/6.md"
                }]
            }, {
                "text": "提摩太后书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/提摩太后书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/提摩太后书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/提摩太后书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/提摩太后书/4.md"
                }]
            }, {
                "text": "歌罗西书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/歌罗西书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/歌罗西书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/歌罗西书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/歌罗西书/4.md"
                }]
            }, {
                "text": "犹大书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/犹大书/1.md"
                }]
            }, {
                "text": "约翰一书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约翰一书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/约翰一书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/约翰一书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/约翰一书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/约翰一书/5.md"
                }]
            }, {
                "text": "约翰三书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约翰三书/1.md"
                }]
            }, {
                "text": "约翰二书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约翰二书/1.md"
                }]
            }, {
                "text": "约翰福音",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约翰福音/1.md"
                }, {
                    "text": "第10章",
                    "link": "/约翰福音/10.md"
                }, {
                    "text": "第11章",
                    "link": "/约翰福音/11.md"
                }, {
                    "text": "第12章",
                    "link": "/约翰福音/12.md"
                }, {
                    "text": "第13章",
                    "link": "/约翰福音/13.md"
                }, {
                    "text": "第14章",
                    "link": "/约翰福音/14.md"
                }, {
                    "text": "第15章",
                    "link": "/约翰福音/15.md"
                }, {
                    "text": "第16章",
                    "link": "/约翰福音/16.md"
                }, {
                    "text": "第17章",
                    "link": "/约翰福音/17.md"
                }, {
                    "text": "第18章",
                    "link": "/约翰福音/18.md"
                }, {
                    "text": "第19章",
                    "link": "/约翰福音/19.md"
                }, {
                    "text": "第2章",
                    "link": "/约翰福音/2.md"
                }, {
                    "text": "第20章",
                    "link": "/约翰福音/20.md"
                }, {
                    "text": "第21章",
                    "link": "/约翰福音/21.md"
                }, {
                    "text": "第3章",
                    "link": "/约翰福音/3.md"
                }, {
                    "text": "第4章",
                    "link": "/约翰福音/4.md"
                }, {
                    "text": "第5章",
                    "link": "/约翰福音/5.md"
                }, {
                    "text": "第6章",
                    "link": "/约翰福音/6.md"
                }, {
                    "text": "第7章",
                    "link": "/约翰福音/7.md"
                }, {
                    "text": "第8章",
                    "link": "/约翰福音/8.md"
                }, {
                    "text": "第9章",
                    "link": "/约翰福音/9.md"
                }]
            }, {
                "text": "罗马书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/罗马书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/罗马书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/罗马书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/罗马书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/罗马书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/罗马书/14.md"
                }, {
                    "text": "第15章",
                    "link": "/罗马书/15.md"
                }, {
                    "text": "第16章",
                    "link": "/罗马书/16.md"
                }, {
                    "text": "第2章",
                    "link": "/罗马书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/罗马书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/罗马书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/罗马书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/罗马书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/罗马书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/罗马书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/罗马书/9.md"
                }]
            }, {
                "text": "腓利门书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/腓利门书/1.md"
                }]
            }, {
                "text": "腓立比书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/腓立比书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/腓立比书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/腓立比书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/腓立比书/4.md"
                }]
            }, {
                "text": "路加福音",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/路加福音/1.md"
                }, {
                    "text": "第10章",
                    "link": "/路加福音/10.md"
                }, {
                    "text": "第11章",
                    "link": "/路加福音/11.md"
                }, {
                    "text": "第12章",
                    "link": "/路加福音/12.md"
                }, {
                    "text": "第13章",
                    "link": "/路加福音/13.md"
                }, {
                    "text": "第14章",
                    "link": "/路加福音/14.md"
                }, {
                    "text": "第15章",
                    "link": "/路加福音/15.md"
                }, {
                    "text": "第16章",
                    "link": "/路加福音/16.md"
                }, {
                    "text": "第17章",
                    "link": "/路加福音/17.md"
                }, {
                    "text": "第18章",
                    "link": "/路加福音/18.md"
                }, {
                    "text": "第19章",
                    "link": "/路加福音/19.md"
                }, {
                    "text": "第2章",
                    "link": "/路加福音/2.md"
                }, {
                    "text": "第20章",
                    "link": "/路加福音/20.md"
                }, {
                    "text": "第21章",
                    "link": "/路加福音/21.md"
                }, {
                    "text": "第22章",
                    "link": "/路加福音/22.md"
                }, {
                    "text": "第23章",
                    "link": "/路加福音/23.md"
                }, {
                    "text": "第24章",
                    "link": "/路加福音/24.md"
                }, {
                    "text": "第3章",
                    "link": "/路加福音/3.md"
                }, {
                    "text": "第4章",
                    "link": "/路加福音/4.md"
                }, {
                    "text": "第5章",
                    "link": "/路加福音/5.md"
                }, {
                    "text": "第6章",
                    "link": "/路加福音/6.md"
                }, {
                    "text": "第7章",
                    "link": "/路加福音/7.md"
                }, {
                    "text": "第8章",
                    "link": "/路加福音/8.md"
                }, {
                    "text": "第9章",
                    "link": "/路加福音/9.md"
                }]
            }, {
                "text": "雅各书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/雅各书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/雅各书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/雅各书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/雅各书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/雅各书/5.md"
                }]
            }, {
                "text": "马可福音",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/马可福音/1.md"
                }, {
                    "text": "第10章",
                    "link": "/马可福音/10.md"
                }, {
                    "text": "第11章",
                    "link": "/马可福音/11.md"
                }, {
                    "text": "第12章",
                    "link": "/马可福音/12.md"
                }, {
                    "text": "第13章",
                    "link": "/马可福音/13.md"
                }, {
                    "text": "第14章",
                    "link": "/马可福音/14.md"
                }, {
                    "text": "第15章",
                    "link": "/马可福音/15.md"
                }, {
                    "text": "第16章",
                    "link": "/马可福音/16.md"
                }, {
                    "text": "第2章",
                    "link": "/马可福音/2.md"
                }, {
                    "text": "第3章",
                    "link": "/马可福音/3.md"
                }, {
                    "text": "第4章",
                    "link": "/马可福音/4.md"
                }, {
                    "text": "第5章",
                    "link": "/马可福音/5.md"
                }, {
                    "text": "第6章",
                    "link": "/马可福音/6.md"
                }, {
                    "text": "第7章",
                    "link": "/马可福音/7.md"
                }, {
                    "text": "第8章",
                    "link": "/马可福音/8.md"
                }, {
                    "text": "第9章",
                    "link": "/马可福音/9.md"
                }]
            }, {
                "text": "马太福音",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/马太福音/1.md"
                }, {
                    "text": "第10章",
                    "link": "/马太福音/10.md"
                }, {
                    "text": "第11章",
                    "link": "/马太福音/11.md"
                }, {
                    "text": "第12章",
                    "link": "/马太福音/12.md"
                }, {
                    "text": "第13章",
                    "link": "/马太福音/13.md"
                }, {
                    "text": "第14章",
                    "link": "/马太福音/14.md"
                }, {
                    "text": "第15章",
                    "link": "/马太福音/15.md"
                }, {
                    "text": "第16章",
                    "link": "/马太福音/16.md"
                }, {
                    "text": "第17章",
                    "link": "/马太福音/17.md"
                }, {
                    "text": "第18章",
                    "link": "/马太福音/18.md"
                }, {
                    "text": "第19章",
                    "link": "/马太福音/19.md"
                }, {
                    "text": "第2章",
                    "link": "/马太福音/2.md"
                }, {
                    "text": "第20章",
                    "link": "/马太福音/20.md"
                }, {
                    "text": "第21章",
                    "link": "/马太福音/21.md"
                }, {
                    "text": "第22章",
                    "link": "/马太福音/22.md"
                }, {
                    "text": "第23章",
                    "link": "/马太福音/23.md"
                }, {
                    "text": "第24章",
                    "link": "/马太福音/24.md"
                }, {
                    "text": "第25章",
                    "link": "/马太福音/25.md"
                }, {
                    "text": "第26章",
                    "link": "/马太福音/26.md"
                }, {
                    "text": "第27章",
                    "link": "/马太福音/27.md"
                }, {
                    "text": "第28章",
                    "link": "/马太福音/28.md"
                }, {
                    "text": "第3章",
                    "link": "/马太福音/3.md"
                }, {
                    "text": "第4章",
                    "link": "/马太福音/4.md"
                }, {
                    "text": "第5章",
                    "link": "/马太福音/5.md"
                }, {
                    "text": "第6章",
                    "link": "/马太福音/6.md"
                }, {
                    "text": "第7章",
                    "link": "/马太福音/7.md"
                }, {
                    "text": "第8章",
                    "link": "/马太福音/8.md"
                }, {
                    "text": "第9章",
                    "link": "/马太福音/9.md"
                }]
            }],
            outline: 2,
            outlineTitle: "大纲",
            socialLinks: [{
                icon: "github",
                link: "https://github.com/Lisk809/Lisk"
            }],
            footer: {
                message: '<a href="https://github.com/Lisk809/bible">the Project</a>使用 <a href="https://github.com/KiviBotLab/docs/blob/main/LICENSE">MIT</a> 协议开放源代码\nPower by <a href="https://vitepress.docschina.org/">VitePress</a><br>Made with Love❤️and confidence.',
                copyright: 'Copyright © 2022-PRESENT <a href="https://github.com/Lisk809">Lisk</a>',
            },
            lastUpdatedText: "上次更新",
            docFooter: {
                prev: "上一页",
                next: "下一页",
            },
            editLink: {
                pattern: "https://github.com/Lisk809/bible/edit/main/src/docs/:path",
                text: "在 GitHub 上编辑",
            },
        },
        });