import {
    defineConfig
}
from "vitepress";

export default defineConfig({
    lang: "zh-CN",
    title: "Holy Bible",
    description: "the Holy Bible for Web",
    head: [
        ["link", {
            rel: "preconnect",
            href: "https://unpkg.com"
        }],
        ["link", {
            rel: "dns-prefetch",
            href: "https://unpkg.com"
        }],
        ["script", {
            src: "https://unpkg.com/twemoji@latest/dist/twemoji.min.js"
        }], ],
    lastUpdated: true,
    markdown: {
        theme: "one-dark-pro",
        lineNumbers: true,
    },
    themeConfig: {
        logo: "",
        nav: [{
            text: "文档",
            link: "/intro"
        }, {
            text: "找我",
            items: [{
                items: [{
                    text: "GitHub",
                    link: "https://github.com/Lisk809"
                }, {
                    text: "QQ",
                    link: "https://qm.qq.com/cgi-bin/qm/qr?k=z_MhzXU1RM0HEnIOBmXiERGNuDxpHglV&noverify=0",
                }, ],
            }, ],
        }, ],
        sidebar: [{
            text: "开始",
            collapsible: true,
            items: [{
                text: "简介",
                link: "/intro"
            }],
        }, {
            text: "bible",
            collapsible: true,
            items: [{
                "text": "以斯帖记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/以斯帖记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/以斯帖记/10.md"
                }, {
                    "text": "第2章",
                    "link": "/以斯帖记/2.md"
                }, {
                    "text": "第3章",
                    "link": "/以斯帖记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/以斯帖记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/以斯帖记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/以斯帖记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/以斯帖记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/以斯帖记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/以斯帖记/9.md"
                }]
            }, {
                "text": "以斯拉记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/以斯拉记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/以斯拉记/10.md"
                }, {
                    "text": "第2章",
                    "link": "/以斯拉记/2.md"
                }, {
                    "text": "第3章",
                    "link": "/以斯拉记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/以斯拉记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/以斯拉记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/以斯拉记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/以斯拉记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/以斯拉记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/以斯拉记/9.md"
                }]
            }, {
                "text": "以西结书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/以西结书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/以西结书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/以西结书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/以西结书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/以西结书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/以西结书/14.md"
                }, {
                    "text": "第15章",
                    "link": "/以西结书/15.md"
                }, {
                    "text": "第16章",
                    "link": "/以西结书/16.md"
                }, {
                    "text": "第17章",
                    "link": "/以西结书/17.md"
                }, {
                    "text": "第18章",
                    "link": "/以西结书/18.md"
                }, {
                    "text": "第19章",
                    "link": "/以西结书/19.md"
                }, {
                    "text": "第2章",
                    "link": "/以西结书/2.md"
                }, {
                    "text": "第20章",
                    "link": "/以西结书/20.md"
                }, {
                    "text": "第21章",
                    "link": "/以西结书/21.md"
                }, {
                    "text": "第22章",
                    "link": "/以西结书/22.md"
                }, {
                    "text": "第23章",
                    "link": "/以西结书/23.md"
                }, {
                    "text": "第24章",
                    "link": "/以西结书/24.md"
                }, {
                    "text": "第25章",
                    "link": "/以西结书/25.md"
                }, {
                    "text": "第26章",
                    "link": "/以西结书/26.md"
                }, {
                    "text": "第27章",
                    "link": "/以西结书/27.md"
                }, {
                    "text": "第28章",
                    "link": "/以西结书/28.md"
                }, {
                    "text": "第29章",
                    "link": "/以西结书/29.md"
                }, {
                    "text": "第3章",
                    "link": "/以西结书/3.md"
                }, {
                    "text": "第30章",
                    "link": "/以西结书/30.md"
                }, {
                    "text": "第31章",
                    "link": "/以西结书/31.md"
                }, {
                    "text": "第32章",
                    "link": "/以西结书/32.md"
                }, {
                    "text": "第33章",
                    "link": "/以西结书/33.md"
                }, {
                    "text": "第34章",
                    "link": "/以西结书/34.md"
                }, {
                    "text": "第35章",
                    "link": "/以西结书/35.md"
                }, {
                    "text": "第36章",
                    "link": "/以西结书/36.md"
                }, {
                    "text": "第37章",
                    "link": "/以西结书/37.md"
                }, {
                    "text": "第38章",
                    "link": "/以西结书/38.md"
                }, {
                    "text": "第39章",
                    "link": "/以西结书/39.md"
                }, {
                    "text": "第4章",
                    "link": "/以西结书/4.md"
                }, {
                    "text": "第40章",
                    "link": "/以西结书/40.md"
                }, {
                    "text": "第41章",
                    "link": "/以西结书/41.md"
                }, {
                    "text": "第42章",
                    "link": "/以西结书/42.md"
                }, {
                    "text": "第43章",
                    "link": "/以西结书/43.md"
                }, {
                    "text": "第44章",
                    "link": "/以西结书/44.md"
                }, {
                    "text": "第45章",
                    "link": "/以西结书/45.md"
                }, {
                    "text": "第46章",
                    "link": "/以西结书/46.md"
                }, {
                    "text": "第47章",
                    "link": "/以西结书/47.md"
                }, {
                    "text": "第48章",
                    "link": "/以西结书/48.md"
                }, {
                    "text": "第5章",
                    "link": "/以西结书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/以西结书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/以西结书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/以西结书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/以西结书/9.md"
                }]
            }, {
                "text": "以赛亚书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/以赛亚书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/以赛亚书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/以赛亚书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/以赛亚书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/以赛亚书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/以赛亚书/14.md"
                }, {
                    "text": "第15章",
                    "link": "/以赛亚书/15.md"
                }, {
                    "text": "第16章",
                    "link": "/以赛亚书/16.md"
                }, {
                    "text": "第17章",
                    "link": "/以赛亚书/17.md"
                }, {
                    "text": "第18章",
                    "link": "/以赛亚书/18.md"
                }, {
                    "text": "第19章",
                    "link": "/以赛亚书/19.md"
                }, {
                    "text": "第2章",
                    "link": "/以赛亚书/2.md"
                }, {
                    "text": "第20章",
                    "link": "/以赛亚书/20.md"
                }, {
                    "text": "第21章",
                    "link": "/以赛亚书/21.md"
                }, {
                    "text": "第22章",
                    "link": "/以赛亚书/22.md"
                }, {
                    "text": "第23章",
                    "link": "/以赛亚书/23.md"
                }, {
                    "text": "第24章",
                    "link": "/以赛亚书/24.md"
                }, {
                    "text": "第25章",
                    "link": "/以赛亚书/25.md"
                }, {
                    "text": "第26章",
                    "link": "/以赛亚书/26.md"
                }, {
                    "text": "第27章",
                    "link": "/以赛亚书/27.md"
                }, {
                    "text": "第28章",
                    "link": "/以赛亚书/28.md"
                }, {
                    "text": "第29章",
                    "link": "/以赛亚书/29.md"
                }, {
                    "text": "第3章",
                    "link": "/以赛亚书/3.md"
                }, {
                    "text": "第30章",
                    "link": "/以赛亚书/30.md"
                }, {
                    "text": "第31章",
                    "link": "/以赛亚书/31.md"
                }, {
                    "text": "第32章",
                    "link": "/以赛亚书/32.md"
                }, {
                    "text": "第33章",
                    "link": "/以赛亚书/33.md"
                }, {
                    "text": "第34章",
                    "link": "/以赛亚书/34.md"
                }, {
                    "text": "第35章",
                    "link": "/以赛亚书/35.md"
                }, {
                    "text": "第36章",
                    "link": "/以赛亚书/36.md"
                }, {
                    "text": "第37章",
                    "link": "/以赛亚书/37.md"
                }, {
                    "text": "第38章",
                    "link": "/以赛亚书/38.md"
                }, {
                    "text": "第39章",
                    "link": "/以赛亚书/39.md"
                }, {
                    "text": "第4章",
                    "link": "/以赛亚书/4.md"
                }, {
                    "text": "第40章",
                    "link": "/以赛亚书/40.md"
                }, {
                    "text": "第41章",
                    "link": "/以赛亚书/41.md"
                }, {
                    "text": "第42章",
                    "link": "/以赛亚书/42.md"
                }, {
                    "text": "第43章",
                    "link": "/以赛亚书/43.md"
                }, {
                    "text": "第44章",
                    "link": "/以赛亚书/44.md"
                }, {
                    "text": "第45章",
                    "link": "/以赛亚书/45.md"
                }, {
                    "text": "第46章",
                    "link": "/以赛亚书/46.md"
                }, {
                    "text": "第47章",
                    "link": "/以赛亚书/47.md"
                }, {
                    "text": "第48章",
                    "link": "/以赛亚书/48.md"
                }, {
                    "text": "第49章",
                    "link": "/以赛亚书/49.md"
                }, {
                    "text": "第5章",
                    "link": "/以赛亚书/5.md"
                }, {
                    "text": "第50章",
                    "link": "/以赛亚书/50.md"
                }, {
                    "text": "第51章",
                    "link": "/以赛亚书/51.md"
                }, {
                    "text": "第52章",
                    "link": "/以赛亚书/52.md"
                }, {
                    "text": "第53章",
                    "link": "/以赛亚书/53.md"
                }, {
                    "text": "第54章",
                    "link": "/以赛亚书/54.md"
                }, {
                    "text": "第55章",
                    "link": "/以赛亚书/55.md"
                }, {
                    "text": "第56章",
                    "link": "/以赛亚书/56.md"
                }, {
                    "text": "第57章",
                    "link": "/以赛亚书/57.md"
                }, {
                    "text": "第58章",
                    "link": "/以赛亚书/58.md"
                }, {
                    "text": "第59章",
                    "link": "/以赛亚书/59.md"
                }, {
                    "text": "第6章",
                    "link": "/以赛亚书/6.md"
                }, {
                    "text": "第60章",
                    "link": "/以赛亚书/60.md"
                }, {
                    "text": "第61章",
                    "link": "/以赛亚书/61.md"
                }, {
                    "text": "第62章",
                    "link": "/以赛亚书/62.md"
                }, {
                    "text": "第63章",
                    "link": "/以赛亚书/63.md"
                }, {
                    "text": "第64章",
                    "link": "/以赛亚书/64.md"
                }, {
                    "text": "第65章",
                    "link": "/以赛亚书/65.md"
                }, {
                    "text": "第66章",
                    "link": "/以赛亚书/66.md"
                }, {
                    "text": "第7章",
                    "link": "/以赛亚书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/以赛亚书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/以赛亚书/9.md"
                }]
            }, {
                "text": "传道书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/传道书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/传道书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/传道书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/传道书/12.md"
                }, {
                    "text": "第2章",
                    "link": "/传道书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/传道书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/传道书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/传道书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/传道书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/传道书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/传道书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/传道书/9.md"
                }]
            }, {
                "text": "但以理书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/但以理书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/但以理书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/但以理书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/但以理书/12.md"
                }, {
                    "text": "第2章",
                    "link": "/但以理书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/但以理书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/但以理书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/但以理书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/但以理书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/但以理书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/但以理书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/但以理书/9.md"
                }]
            }, {
                "text": "何西阿书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/何西阿书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/何西阿书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/何西阿书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/何西阿书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/何西阿书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/何西阿书/14.md"
                }, {
                    "text": "第2章",
                    "link": "/何西阿书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/何西阿书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/何西阿书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/何西阿书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/何西阿书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/何西阿书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/何西阿书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/何西阿书/9.md"
                }]
            }, {
                "text": "俄巴底亚书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/俄巴底亚书/1.md"
                }]
            }, {
                "text": "出埃及记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/出埃及记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/出埃及记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/出埃及记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/出埃及记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/出埃及记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/出埃及记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/出埃及记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/出埃及记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/出埃及记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/出埃及记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/出埃及记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/出埃及记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/出埃及记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/出埃及记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/出埃及记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/出埃及记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/出埃及记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/出埃及记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/出埃及记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/出埃及记/27.md"
                }, {
                    "text": "第28章",
                    "link": "/出埃及记/28.md"
                }, {
                    "text": "第29章",
                    "link": "/出埃及记/29.md"
                }, {
                    "text": "第3章",
                    "link": "/出埃及记/3.md"
                }, {
                    "text": "第30章",
                    "link": "/出埃及记/30.md"
                }, {
                    "text": "第31章",
                    "link": "/出埃及记/31.md"
                }, {
                    "text": "第32章",
                    "link": "/出埃及记/32.md"
                }, {
                    "text": "第33章",
                    "link": "/出埃及记/33.md"
                }, {
                    "text": "第34章",
                    "link": "/出埃及记/34.md"
                }, {
                    "text": "第35章",
                    "link": "/出埃及记/35.md"
                }, {
                    "text": "第36章",
                    "link": "/出埃及记/36.md"
                }, {
                    "text": "第37章",
                    "link": "/出埃及记/37.md"
                }, {
                    "text": "第38章",
                    "link": "/出埃及记/38.md"
                }, {
                    "text": "第39章",
                    "link": "/出埃及记/39.md"
                }, {
                    "text": "第4章",
                    "link": "/出埃及记/4.md"
                }, {
                    "text": "第40章",
                    "link": "/出埃及记/40.md"
                }, {
                    "text": "第5章",
                    "link": "/出埃及记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/出埃及记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/出埃及记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/出埃及记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/出埃及记/9.md"
                }]
            }, {
                "text": "列王记上",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/列王记上/1.md"
                }, {
                    "text": "第10章",
                    "link": "/列王记上/10.md"
                }, {
                    "text": "第11章",
                    "link": "/列王记上/11.md"
                }, {
                    "text": "第12章",
                    "link": "/列王记上/12.md"
                }, {
                    "text": "第13章",
                    "link": "/列王记上/13.md"
                }, {
                    "text": "第14章",
                    "link": "/列王记上/14.md"
                }, {
                    "text": "第15章",
                    "link": "/列王记上/15.md"
                }, {
                    "text": "第16章",
                    "link": "/列王记上/16.md"
                }, {
                    "text": "第17章",
                    "link": "/列王记上/17.md"
                }, {
                    "text": "第18章",
                    "link": "/列王记上/18.md"
                }, {
                    "text": "第19章",
                    "link": "/列王记上/19.md"
                }, {
                    "text": "第2章",
                    "link": "/列王记上/2.md"
                }, {
                    "text": "第20章",
                    "link": "/列王记上/20.md"
                }, {
                    "text": "第21章",
                    "link": "/列王记上/21.md"
                }, {
                    "text": "第22章",
                    "link": "/列王记上/22.md"
                }, {
                    "text": "第3章",
                    "link": "/列王记上/3.md"
                }, {
                    "text": "第4章",
                    "link": "/列王记上/4.md"
                }, {
                    "text": "第5章",
                    "link": "/列王记上/5.md"
                }, {
                    "text": "第6章",
                    "link": "/列王记上/6.md"
                }, {
                    "text": "第7章",
                    "link": "/列王记上/7.md"
                }, {
                    "text": "第8章",
                    "link": "/列王记上/8.md"
                }, {
                    "text": "第9章",
                    "link": "/列王记上/9.md"
                }]
            }, {
                "text": "列王记下",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/列王记下/1.md"
                }, {
                    "text": "第10章",
                    "link": "/列王记下/10.md"
                }, {
                    "text": "第11章",
                    "link": "/列王记下/11.md"
                }, {
                    "text": "第12章",
                    "link": "/列王记下/12.md"
                }, {
                    "text": "第13章",
                    "link": "/列王记下/13.md"
                }, {
                    "text": "第14章",
                    "link": "/列王记下/14.md"
                }, {
                    "text": "第15章",
                    "link": "/列王记下/15.md"
                }, {
                    "text": "第16章",
                    "link": "/列王记下/16.md"
                }, {
                    "text": "第17章",
                    "link": "/列王记下/17.md"
                }, {
                    "text": "第18章",
                    "link": "/列王记下/18.md"
                }, {
                    "text": "第19章",
                    "link": "/列王记下/19.md"
                }, {
                    "text": "第2章",
                    "link": "/列王记下/2.md"
                }, {
                    "text": "第20章",
                    "link": "/列王记下/20.md"
                }, {
                    "text": "第21章",
                    "link": "/列王记下/21.md"
                }, {
                    "text": "第22章",
                    "link": "/列王记下/22.md"
                }, {
                    "text": "第23章",
                    "link": "/列王记下/23.md"
                }, {
                    "text": "第24章",
                    "link": "/列王记下/24.md"
                }, {
                    "text": "第25章",
                    "link": "/列王记下/25.md"
                }, {
                    "text": "第3章",
                    "link": "/列王记下/3.md"
                }, {
                    "text": "第4章",
                    "link": "/列王记下/4.md"
                }, {
                    "text": "第5章",
                    "link": "/列王记下/5.md"
                }, {
                    "text": "第6章",
                    "link": "/列王记下/6.md"
                }, {
                    "text": "第7章",
                    "link": "/列王记下/7.md"
                }, {
                    "text": "第8章",
                    "link": "/列王记下/8.md"
                }, {
                    "text": "第9章",
                    "link": "/列王记下/9.md"
                }]
            }, {
                "text": "创世记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/创世记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/创世记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/创世记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/创世记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/创世记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/创世记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/创世记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/创世记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/创世记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/创世记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/创世记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/创世记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/创世记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/创世记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/创世记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/创世记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/创世记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/创世记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/创世记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/创世记/27.md"
                }, {
                    "text": "第28章",
                    "link": "/创世记/28.md"
                }, {
                    "text": "第29章",
                    "link": "/创世记/29.md"
                }, {
                    "text": "第3章",
                    "link": "/创世记/3.md"
                }, {
                    "text": "第30章",
                    "link": "/创世记/30.md"
                }, {
                    "text": "第31章",
                    "link": "/创世记/31.md"
                }, {
                    "text": "第32章",
                    "link": "/创世记/32.md"
                }, {
                    "text": "第33章",
                    "link": "/创世记/33.md"
                }, {
                    "text": "第34章",
                    "link": "/创世记/34.md"
                }, {
                    "text": "第35章",
                    "link": "/创世记/35.md"
                }, {
                    "text": "第36章",
                    "link": "/创世记/36.md"
                }, {
                    "text": "第37章",
                    "link": "/创世记/37.md"
                }, {
                    "text": "第38章",
                    "link": "/创世记/38.md"
                }, {
                    "text": "第39章",
                    "link": "/创世记/39.md"
                }, {
                    "text": "第4章",
                    "link": "/创世记/4.md"
                }, {
                    "text": "第40章",
                    "link": "/创世记/40.md"
                }, {
                    "text": "第41章",
                    "link": "/创世记/41.md"
                }, {
                    "text": "第42章",
                    "link": "/创世记/42.md"
                }, {
                    "text": "第43章",
                    "link": "/创世记/43.md"
                }, {
                    "text": "第44章",
                    "link": "/创世记/44.md"
                }, {
                    "text": "第45章",
                    "link": "/创世记/45.md"
                }, {
                    "text": "第46章",
                    "link": "/创世记/46.md"
                }, {
                    "text": "第47章",
                    "link": "/创世记/47.md"
                }, {
                    "text": "第48章",
                    "link": "/创世记/48.md"
                }, {
                    "text": "第49章",
                    "link": "/创世记/49.md"
                }, {
                    "text": "第5章",
                    "link": "/创世记/5.md"
                }, {
                    "text": "第50章",
                    "link": "/创世记/50.md"
                }, {
                    "text": "第6章",
                    "link": "/创世记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/创世记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/创世记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/创世记/9.md"
                }]
            }, {
                "text": "利未记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/利未记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/利未记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/利未记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/利未记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/利未记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/利未记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/利未记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/利未记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/利未记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/利未记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/利未记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/利未记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/利未记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/利未记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/利未记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/利未记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/利未记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/利未记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/利未记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/利未记/27.md"
                }, {
                    "text": "第3章",
                    "link": "/利未记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/利未记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/利未记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/利未记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/利未记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/利未记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/利未记/9.md"
                }]
            }, {
                "text": "历代志上",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/历代志上/1.md"
                }, {
                    "text": "第10章",
                    "link": "/历代志上/10.md"
                }, {
                    "text": "第11章",
                    "link": "/历代志上/11.md"
                }, {
                    "text": "第12章",
                    "link": "/历代志上/12.md"
                }, {
                    "text": "第13章",
                    "link": "/历代志上/13.md"
                }, {
                    "text": "第14章",
                    "link": "/历代志上/14.md"
                }, {
                    "text": "第15章",
                    "link": "/历代志上/15.md"
                }, {
                    "text": "第16章",
                    "link": "/历代志上/16.md"
                }, {
                    "text": "第17章",
                    "link": "/历代志上/17.md"
                }, {
                    "text": "第18章",
                    "link": "/历代志上/18.md"
                }, {
                    "text": "第19章",
                    "link": "/历代志上/19.md"
                }, {
                    "text": "第2章",
                    "link": "/历代志上/2.md"
                }, {
                    "text": "第20章",
                    "link": "/历代志上/20.md"
                }, {
                    "text": "第21章",
                    "link": "/历代志上/21.md"
                }, {
                    "text": "第22章",
                    "link": "/历代志上/22.md"
                }, {
                    "text": "第23章",
                    "link": "/历代志上/23.md"
                }, {
                    "text": "第24章",
                    "link": "/历代志上/24.md"
                }, {
                    "text": "第25章",
                    "link": "/历代志上/25.md"
                }, {
                    "text": "第26章",
                    "link": "/历代志上/26.md"
                }, {
                    "text": "第27章",
                    "link": "/历代志上/27.md"
                }, {
                    "text": "第28章",
                    "link": "/历代志上/28.md"
                }, {
                    "text": "第29章",
                    "link": "/历代志上/29.md"
                }, {
                    "text": "第3章",
                    "link": "/历代志上/3.md"
                }, {
                    "text": "第4章",
                    "link": "/历代志上/4.md"
                }, {
                    "text": "第5章",
                    "link": "/历代志上/5.md"
                }, {
                    "text": "第6章",
                    "link": "/历代志上/6.md"
                }, {
                    "text": "第7章",
                    "link": "/历代志上/7.md"
                }, {
                    "text": "第8章",
                    "link": "/历代志上/8.md"
                }, {
                    "text": "第9章",
                    "link": "/历代志上/9.md"
                }]
            }, {
                "text": "历代志下",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/历代志下/1.md"
                }, {
                    "text": "第10章",
                    "link": "/历代志下/10.md"
                }, {
                    "text": "第11章",
                    "link": "/历代志下/11.md"
                }, {
                    "text": "第12章",
                    "link": "/历代志下/12.md"
                }, {
                    "text": "第13章",
                    "link": "/历代志下/13.md"
                }, {
                    "text": "第14章",
                    "link": "/历代志下/14.md"
                }, {
                    "text": "第15章",
                    "link": "/历代志下/15.md"
                }, {
                    "text": "第16章",
                    "link": "/历代志下/16.md"
                }, {
                    "text": "第17章",
                    "link": "/历代志下/17.md"
                }, {
                    "text": "第18章",
                    "link": "/历代志下/18.md"
                }, {
                    "text": "第19章",
                    "link": "/历代志下/19.md"
                }, {
                    "text": "第2章",
                    "link": "/历代志下/2.md"
                }, {
                    "text": "第20章",
                    "link": "/历代志下/20.md"
                }, {
                    "text": "第21章",
                    "link": "/历代志下/21.md"
                }, {
                    "text": "第22章",
                    "link": "/历代志下/22.md"
                }, {
                    "text": "第23章",
                    "link": "/历代志下/23.md"
                }, {
                    "text": "第24章",
                    "link": "/历代志下/24.md"
                }, {
                    "text": "第25章",
                    "link": "/历代志下/25.md"
                }, {
                    "text": "第26章",
                    "link": "/历代志下/26.md"
                }, {
                    "text": "第27章",
                    "link": "/历代志下/27.md"
                }, {
                    "text": "第28章",
                    "link": "/历代志下/28.md"
                }, {
                    "text": "第29章",
                    "link": "/历代志下/29.md"
                }, {
                    "text": "第3章",
                    "link": "/历代志下/3.md"
                }, {
                    "text": "第30章",
                    "link": "/历代志下/30.md"
                }, {
                    "text": "第31章",
                    "link": "/历代志下/31.md"
                }, {
                    "text": "第32章",
                    "link": "/历代志下/32.md"
                }, {
                    "text": "第33章",
                    "link": "/历代志下/33.md"
                }, {
                    "text": "第34章",
                    "link": "/历代志下/34.md"
                }, {
                    "text": "第35章",
                    "link": "/历代志下/35.md"
                }, {
                    "text": "第36章",
                    "link": "/历代志下/36.md"
                }, {
                    "text": "第4章",
                    "link": "/历代志下/4.md"
                }, {
                    "text": "第5章",
                    "link": "/历代志下/5.md"
                }, {
                    "text": "第6章",
                    "link": "/历代志下/6.md"
                }, {
                    "text": "第7章",
                    "link": "/历代志下/7.md"
                }, {
                    "text": "第8章",
                    "link": "/历代志下/8.md"
                }, {
                    "text": "第9章",
                    "link": "/历代志下/9.md"
                }]
            }, {
                "text": "哈巴谷书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/哈巴谷书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/哈巴谷书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/哈巴谷书/3.md"
                }]
            }, {
                "text": "哈该书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/哈该书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/哈该书/2.md"
                }]
            }, {
                "text": "士师记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/士师记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/士师记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/士师记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/士师记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/士师记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/士师记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/士师记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/士师记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/士师记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/士师记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/士师记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/士师记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/士师记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/士师记/21.md"
                }, {
                    "text": "第3章",
                    "link": "/士师记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/士师记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/士师记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/士师记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/士师记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/士师记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/士师记/9.md"
                }]
            }, {
                "text": "尼希米记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/尼希米记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/尼希米记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/尼希米记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/尼希米记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/尼希米记/13.md"
                }, {
                    "text": "第2章",
                    "link": "/尼希米记/2.md"
                }, {
                    "text": "第3章",
                    "link": "/尼希米记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/尼希米记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/尼希米记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/尼希米记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/尼希米记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/尼希米记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/尼希米记/9.md"
                }]
            }, {
                "text": "弥迦书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/弥迦书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/弥迦书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/弥迦书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/弥迦书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/弥迦书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/弥迦书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/弥迦书/7.md"
                }]
            }, {
                "text": "撒母耳记上",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/撒母耳记上/1.md"
                }, {
                    "text": "第10章",
                    "link": "/撒母耳记上/10.md"
                }, {
                    "text": "第11章",
                    "link": "/撒母耳记上/11.md"
                }, {
                    "text": "第12章",
                    "link": "/撒母耳记上/12.md"
                }, {
                    "text": "第13章",
                    "link": "/撒母耳记上/13.md"
                }, {
                    "text": "第14章",
                    "link": "/撒母耳记上/14.md"
                }, {
                    "text": "第15章",
                    "link": "/撒母耳记上/15.md"
                }, {
                    "text": "第16章",
                    "link": "/撒母耳记上/16.md"
                }, {
                    "text": "第17章",
                    "link": "/撒母耳记上/17.md"
                }, {
                    "text": "第18章",
                    "link": "/撒母耳记上/18.md"
                }, {
                    "text": "第19章",
                    "link": "/撒母耳记上/19.md"
                }, {
                    "text": "第2章",
                    "link": "/撒母耳记上/2.md"
                }, {
                    "text": "第20章",
                    "link": "/撒母耳记上/20.md"
                }, {
                    "text": "第21章",
                    "link": "/撒母耳记上/21.md"
                }, {
                    "text": "第22章",
                    "link": "/撒母耳记上/22.md"
                }, {
                    "text": "第23章",
                    "link": "/撒母耳记上/23.md"
                }, {
                    "text": "第24章",
                    "link": "/撒母耳记上/24.md"
                }, {
                    "text": "第25章",
                    "link": "/撒母耳记上/25.md"
                }, {
                    "text": "第26章",
                    "link": "/撒母耳记上/26.md"
                }, {
                    "text": "第27章",
                    "link": "/撒母耳记上/27.md"
                }, {
                    "text": "第28章",
                    "link": "/撒母耳记上/28.md"
                }, {
                    "text": "第29章",
                    "link": "/撒母耳记上/29.md"
                }, {
                    "text": "第3章",
                    "link": "/撒母耳记上/3.md"
                }, {
                    "text": "第30章",
                    "link": "/撒母耳记上/30.md"
                }, {
                    "text": "第31章",
                    "link": "/撒母耳记上/31.md"
                }, {
                    "text": "第4章",
                    "link": "/撒母耳记上/4.md"
                }, {
                    "text": "第5章",
                    "link": "/撒母耳记上/5.md"
                }, {
                    "text": "第6章",
                    "link": "/撒母耳记上/6.md"
                }, {
                    "text": "第7章",
                    "link": "/撒母耳记上/7.md"
                }, {
                    "text": "第8章",
                    "link": "/撒母耳记上/8.md"
                }, {
                    "text": "第9章",
                    "link": "/撒母耳记上/9.md"
                }]
            }, {
                "text": "撒母耳记下",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/撒母耳记下/1.md"
                }, {
                    "text": "第10章",
                    "link": "/撒母耳记下/10.md"
                }, {
                    "text": "第11章",
                    "link": "/撒母耳记下/11.md"
                }, {
                    "text": "第12章",
                    "link": "/撒母耳记下/12.md"
                }, {
                    "text": "第13章",
                    "link": "/撒母耳记下/13.md"
                }, {
                    "text": "第14章",
                    "link": "/撒母耳记下/14.md"
                }, {
                    "text": "第15章",
                    "link": "/撒母耳记下/15.md"
                }, {
                    "text": "第16章",
                    "link": "/撒母耳记下/16.md"
                }, {
                    "text": "第17章",
                    "link": "/撒母耳记下/17.md"
                }, {
                    "text": "第18章",
                    "link": "/撒母耳记下/18.md"
                }, {
                    "text": "第19章",
                    "link": "/撒母耳记下/19.md"
                }, {
                    "text": "第2章",
                    "link": "/撒母耳记下/2.md"
                }, {
                    "text": "第20章",
                    "link": "/撒母耳记下/20.md"
                }, {
                    "text": "第21章",
                    "link": "/撒母耳记下/21.md"
                }, {
                    "text": "第22章",
                    "link": "/撒母耳记下/22.md"
                }, {
                    "text": "第23章",
                    "link": "/撒母耳记下/23.md"
                }, {
                    "text": "第24章",
                    "link": "/撒母耳记下/24.md"
                }, {
                    "text": "第3章",
                    "link": "/撒母耳记下/3.md"
                }, {
                    "text": "第4章",
                    "link": "/撒母耳记下/4.md"
                }, {
                    "text": "第5章",
                    "link": "/撒母耳记下/5.md"
                }, {
                    "text": "第6章",
                    "link": "/撒母耳记下/6.md"
                }, {
                    "text": "第7章",
                    "link": "/撒母耳记下/7.md"
                }, {
                    "text": "第8章",
                    "link": "/撒母耳记下/8.md"
                }, {
                    "text": "第9章",
                    "link": "/撒母耳记下/9.md"
                }]
            }, {
                "text": "撒迦利亚书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/撒迦利亚书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/撒迦利亚书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/撒迦利亚书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/撒迦利亚书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/撒迦利亚书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/撒迦利亚书/14.md"
                }, {
                    "text": "第2章",
                    "link": "/撒迦利亚书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/撒迦利亚书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/撒迦利亚书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/撒迦利亚书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/撒迦利亚书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/撒迦利亚书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/撒迦利亚书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/撒迦利亚书/9.md"
                }]
            }, {
                "text": "民数记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/民数记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/民数记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/民数记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/民数记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/民数记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/民数记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/民数记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/民数记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/民数记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/民数记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/民数记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/民数记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/民数记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/民数记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/民数记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/民数记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/民数记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/民数记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/民数记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/民数记/27.md"
                }, {
                    "text": "第28章",
                    "link": "/民数记/28.md"
                }, {
                    "text": "第29章",
                    "link": "/民数记/29.md"
                }, {
                    "text": "第3章",
                    "link": "/民数记/3.md"
                }, {
                    "text": "第30章",
                    "link": "/民数记/30.md"
                }, {
                    "text": "第31章",
                    "link": "/民数记/31.md"
                }, {
                    "text": "第32章",
                    "link": "/民数记/32.md"
                }, {
                    "text": "第33章",
                    "link": "/民数记/33.md"
                }, {
                    "text": "第34章",
                    "link": "/民数记/34.md"
                }, {
                    "text": "第35章",
                    "link": "/民数记/35.md"
                }, {
                    "text": "第36章",
                    "link": "/民数记/36.md"
                }, {
                    "text": "第4章",
                    "link": "/民数记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/民数记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/民数记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/民数记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/民数记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/民数记/9.md"
                }]
            }, {
                "text": "玛拉基书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/玛拉基书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/玛拉基书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/玛拉基书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/玛拉基书/4.md"
                }]
            }, {
                "text": "申命记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/申命记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/申命记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/申命记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/申命记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/申命记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/申命记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/申命记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/申命记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/申命记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/申命记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/申命记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/申命记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/申命记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/申命记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/申命记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/申命记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/申命记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/申命记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/申命记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/申命记/27.md"
                }, {
                    "text": "第28章",
                    "link": "/申命记/28.md"
                }, {
                    "text": "第29章",
                    "link": "/申命记/29.md"
                }, {
                    "text": "第3章",
                    "link": "/申命记/3.md"
                }, {
                    "text": "第30章",
                    "link": "/申命记/30.md"
                }, {
                    "text": "第31章",
                    "link": "/申命记/31.md"
                }, {
                    "text": "第32章",
                    "link": "/申命记/32.md"
                }, {
                    "text": "第33章",
                    "link": "/申命记/33.md"
                }, {
                    "text": "第34章",
                    "link": "/申命记/34.md"
                }, {
                    "text": "第4章",
                    "link": "/申命记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/申命记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/申命记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/申命记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/申命记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/申命记/9.md"
                }]
            }, {
                "text": "箴言",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/箴言/1.md"
                }, {
                    "text": "第10章",
                    "link": "/箴言/10.md"
                }, {
                    "text": "第11章",
                    "link": "/箴言/11.md"
                }, {
                    "text": "第12章",
                    "link": "/箴言/12.md"
                }, {
                    "text": "第13章",
                    "link": "/箴言/13.md"
                }, {
                    "text": "第14章",
                    "link": "/箴言/14.md"
                }, {
                    "text": "第15章",
                    "link": "/箴言/15.md"
                }, {
                    "text": "第16章",
                    "link": "/箴言/16.md"
                }, {
                    "text": "第17章",
                    "link": "/箴言/17.md"
                }, {
                    "text": "第18章",
                    "link": "/箴言/18.md"
                }, {
                    "text": "第19章",
                    "link": "/箴言/19.md"
                }, {
                    "text": "第2章",
                    "link": "/箴言/2.md"
                }, {
                    "text": "第20章",
                    "link": "/箴言/20.md"
                }, {
                    "text": "第21章",
                    "link": "/箴言/21.md"
                }, {
                    "text": "第22章",
                    "link": "/箴言/22.md"
                }, {
                    "text": "第23章",
                    "link": "/箴言/23.md"
                }, {
                    "text": "第24章",
                    "link": "/箴言/24.md"
                }, {
                    "text": "第25章",
                    "link": "/箴言/25.md"
                }, {
                    "text": "第26章",
                    "link": "/箴言/26.md"
                }, {
                    "text": "第27章",
                    "link": "/箴言/27.md"
                }, {
                    "text": "第28章",
                    "link": "/箴言/28.md"
                }, {
                    "text": "第29章",
                    "link": "/箴言/29.md"
                }, {
                    "text": "第3章",
                    "link": "/箴言/3.md"
                }, {
                    "text": "第30章",
                    "link": "/箴言/30.md"
                }, {
                    "text": "第31章",
                    "link": "/箴言/31.md"
                }, {
                    "text": "第4章",
                    "link": "/箴言/4.md"
                }, {
                    "text": "第5章",
                    "link": "/箴言/5.md"
                }, {
                    "text": "第6章",
                    "link": "/箴言/6.md"
                }, {
                    "text": "第7章",
                    "link": "/箴言/7.md"
                }, {
                    "text": "第8章",
                    "link": "/箴言/8.md"
                }, {
                    "text": "第9章",
                    "link": "/箴言/9.md"
                }]
            }, {
                "text": "约书亚记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约书亚记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/约书亚记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/约书亚记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/约书亚记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/约书亚记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/约书亚记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/约书亚记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/约书亚记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/约书亚记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/约书亚记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/约书亚记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/约书亚记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/约书亚记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/约书亚记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/约书亚记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/约书亚记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/约书亚记/24.md"
                }, {
                    "text": "第3章",
                    "link": "/约书亚记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/约书亚记/4.md"
                }, {
                    "text": "第5章",
                    "link": "/约书亚记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/约书亚记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/约书亚记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/约书亚记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/约书亚记/9.md"
                }]
            }, {
                "text": "约伯记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约伯记/1.md"
                }, {
                    "text": "第10章",
                    "link": "/约伯记/10.md"
                }, {
                    "text": "第11章",
                    "link": "/约伯记/11.md"
                }, {
                    "text": "第12章",
                    "link": "/约伯记/12.md"
                }, {
                    "text": "第13章",
                    "link": "/约伯记/13.md"
                }, {
                    "text": "第14章",
                    "link": "/约伯记/14.md"
                }, {
                    "text": "第15章",
                    "link": "/约伯记/15.md"
                }, {
                    "text": "第16章",
                    "link": "/约伯记/16.md"
                }, {
                    "text": "第17章",
                    "link": "/约伯记/17.md"
                }, {
                    "text": "第18章",
                    "link": "/约伯记/18.md"
                }, {
                    "text": "第19章",
                    "link": "/约伯记/19.md"
                }, {
                    "text": "第2章",
                    "link": "/约伯记/2.md"
                }, {
                    "text": "第20章",
                    "link": "/约伯记/20.md"
                }, {
                    "text": "第21章",
                    "link": "/约伯记/21.md"
                }, {
                    "text": "第22章",
                    "link": "/约伯记/22.md"
                }, {
                    "text": "第23章",
                    "link": "/约伯记/23.md"
                }, {
                    "text": "第24章",
                    "link": "/约伯记/24.md"
                }, {
                    "text": "第25章",
                    "link": "/约伯记/25.md"
                }, {
                    "text": "第26章",
                    "link": "/约伯记/26.md"
                }, {
                    "text": "第27章",
                    "link": "/约伯记/27.md"
                }, {
                    "text": "第28章",
                    "link": "/约伯记/28.md"
                }, {
                    "text": "第29章",
                    "link": "/约伯记/29.md"
                }, {
                    "text": "第3章",
                    "link": "/约伯记/3.md"
                }, {
                    "text": "第30章",
                    "link": "/约伯记/30.md"
                }, {
                    "text": "第31章",
                    "link": "/约伯记/31.md"
                }, {
                    "text": "第32章",
                    "link": "/约伯记/32.md"
                }, {
                    "text": "第33章",
                    "link": "/约伯记/33.md"
                }, {
                    "text": "第34章",
                    "link": "/约伯记/34.md"
                }, {
                    "text": "第35章",
                    "link": "/约伯记/35.md"
                }, {
                    "text": "第36章",
                    "link": "/约伯记/36.md"
                }, {
                    "text": "第37章",
                    "link": "/约伯记/37.md"
                }, {
                    "text": "第38章",
                    "link": "/约伯记/38.md"
                }, {
                    "text": "第39章",
                    "link": "/约伯记/39.md"
                }, {
                    "text": "第4章",
                    "link": "/约伯记/4.md"
                }, {
                    "text": "第40章",
                    "link": "/约伯记/40.md"
                }, {
                    "text": "第41章",
                    "link": "/约伯记/41.md"
                }, {
                    "text": "第42章",
                    "link": "/约伯记/42.md"
                }, {
                    "text": "第5章",
                    "link": "/约伯记/5.md"
                }, {
                    "text": "第6章",
                    "link": "/约伯记/6.md"
                }, {
                    "text": "第7章",
                    "link": "/约伯记/7.md"
                }, {
                    "text": "第8章",
                    "link": "/约伯记/8.md"
                }, {
                    "text": "第9章",
                    "link": "/约伯记/9.md"
                }]
            }, {
                "text": "约拿书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约拿书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/约拿书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/约拿书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/约拿书/4.md"
                }]
            }, {
                "text": "约珥书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/约珥书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/约珥书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/约珥书/3.md"
                }]
            }, {
                "text": "耶利米书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/耶利米书/1.md"
                }, {
                    "text": "第10章",
                    "link": "/耶利米书/10.md"
                }, {
                    "text": "第11章",
                    "link": "/耶利米书/11.md"
                }, {
                    "text": "第12章",
                    "link": "/耶利米书/12.md"
                }, {
                    "text": "第13章",
                    "link": "/耶利米书/13.md"
                }, {
                    "text": "第14章",
                    "link": "/耶利米书/14.md"
                }, {
                    "text": "第15章",
                    "link": "/耶利米书/15.md"
                }, {
                    "text": "第16章",
                    "link": "/耶利米书/16.md"
                }, {
                    "text": "第17章",
                    "link": "/耶利米书/17.md"
                }, {
                    "text": "第18章",
                    "link": "/耶利米书/18.md"
                }, {
                    "text": "第19章",
                    "link": "/耶利米书/19.md"
                }, {
                    "text": "第2章",
                    "link": "/耶利米书/2.md"
                }, {
                    "text": "第20章",
                    "link": "/耶利米书/20.md"
                }, {
                    "text": "第21章",
                    "link": "/耶利米书/21.md"
                }, {
                    "text": "第22章",
                    "link": "/耶利米书/22.md"
                }, {
                    "text": "第23章",
                    "link": "/耶利米书/23.md"
                }, {
                    "text": "第24章",
                    "link": "/耶利米书/24.md"
                }, {
                    "text": "第25章",
                    "link": "/耶利米书/25.md"
                }, {
                    "text": "第26章",
                    "link": "/耶利米书/26.md"
                }, {
                    "text": "第27章",
                    "link": "/耶利米书/27.md"
                }, {
                    "text": "第28章",
                    "link": "/耶利米书/28.md"
                }, {
                    "text": "第29章",
                    "link": "/耶利米书/29.md"
                }, {
                    "text": "第3章",
                    "link": "/耶利米书/3.md"
                }, {
                    "text": "第30章",
                    "link": "/耶利米书/30.md"
                }, {
                    "text": "第31章",
                    "link": "/耶利米书/31.md"
                }, {
                    "text": "第32章",
                    "link": "/耶利米书/32.md"
                }, {
                    "text": "第33章",
                    "link": "/耶利米书/33.md"
                }, {
                    "text": "第34章",
                    "link": "/耶利米书/34.md"
                }, {
                    "text": "第35章",
                    "link": "/耶利米书/35.md"
                }, {
                    "text": "第36章",
                    "link": "/耶利米书/36.md"
                }, {
                    "text": "第37章",
                    "link": "/耶利米书/37.md"
                }, {
                    "text": "第38章",
                    "link": "/耶利米书/38.md"
                }, {
                    "text": "第39章",
                    "link": "/耶利米书/39.md"
                }, {
                    "text": "第4章",
                    "link": "/耶利米书/4.md"
                }, {
                    "text": "第40章",
                    "link": "/耶利米书/40.md"
                }, {
                    "text": "第41章",
                    "link": "/耶利米书/41.md"
                }, {
                    "text": "第42章",
                    "link": "/耶利米书/42.md"
                }, {
                    "text": "第43章",
                    "link": "/耶利米书/43.md"
                }, {
                    "text": "第44章",
                    "link": "/耶利米书/44.md"
                }, {
                    "text": "第45章",
                    "link": "/耶利米书/45.md"
                }, {
                    "text": "第46章",
                    "link": "/耶利米书/46.md"
                }, {
                    "text": "第47章",
                    "link": "/耶利米书/47.md"
                }, {
                    "text": "第48章",
                    "link": "/耶利米书/48.md"
                }, {
                    "text": "第49章",
                    "link": "/耶利米书/49.md"
                }, {
                    "text": "第5章",
                    "link": "/耶利米书/5.md"
                }, {
                    "text": "第50章",
                    "link": "/耶利米书/50.md"
                }, {
                    "text": "第51章",
                    "link": "/耶利米书/51.md"
                }, {
                    "text": "第52章",
                    "link": "/耶利米书/52.md"
                }, {
                    "text": "第6章",
                    "link": "/耶利米书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/耶利米书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/耶利米书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/耶利米书/9.md"
                }]
            }, {
                "text": "耶利米哀歌",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/耶利米哀歌/1.md"
                }, {
                    "text": "第2章",
                    "link": "/耶利米哀歌/2.md"
                }, {
                    "text": "第3章",
                    "link": "/耶利米哀歌/3.md"
                }, {
                    "text": "第4章",
                    "link": "/耶利米哀歌/4.md"
                }, {
                    "text": "第5章",
                    "link": "/耶利米哀歌/5.md"
                }]
            }, {
                "text": "西番雅书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/西番雅书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/西番雅书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/西番雅书/3.md"
                }]
            }, {
                "text": "诗篇",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/诗篇/1.md"
                }, {
                    "text": "第10章",
                    "link": "/诗篇/10.md"
                }, {
                    "text": "第100章",
                    "link": "/诗篇/100.md"
                }, {
                    "text": "第101章",
                    "link": "/诗篇/101.md"
                }, {
                    "text": "第102章",
                    "link": "/诗篇/102.md"
                }, {
                    "text": "第103章",
                    "link": "/诗篇/103.md"
                }, {
                    "text": "第104章",
                    "link": "/诗篇/104.md"
                }, {
                    "text": "第105章",
                    "link": "/诗篇/105.md"
                }, {
                    "text": "第106章",
                    "link": "/诗篇/106.md"
                }, {
                    "text": "第107章",
                    "link": "/诗篇/107.md"
                }, {
                    "text": "第108章",
                    "link": "/诗篇/108.md"
                }, {
                    "text": "第109章",
                    "link": "/诗篇/109.md"
                }, {
                    "text": "第11章",
                    "link": "/诗篇/11.md"
                }, {
                    "text": "第110章",
                    "link": "/诗篇/110.md"
                }, {
                    "text": "第111章",
                    "link": "/诗篇/111.md"
                }, {
                    "text": "第112章",
                    "link": "/诗篇/112.md"
                }, {
                    "text": "第113章",
                    "link": "/诗篇/113.md"
                }, {
                    "text": "第114章",
                    "link": "/诗篇/114.md"
                }, {
                    "text": "第115章",
                    "link": "/诗篇/115.md"
                }, {
                    "text": "第116章",
                    "link": "/诗篇/116.md"
                }, {
                    "text": "第117章",
                    "link": "/诗篇/117.md"
                }, {
                    "text": "第118章",
                    "link": "/诗篇/118.md"
                }, {
                    "text": "第119章",
                    "link": "/诗篇/119.md"
                }, {
                    "text": "第12章",
                    "link": "/诗篇/12.md"
                }, {
                    "text": "第120章",
                    "link": "/诗篇/120.md"
                }, {
                    "text": "第121章",
                    "link": "/诗篇/121.md"
                }, {
                    "text": "第122章",
                    "link": "/诗篇/122.md"
                }, {
                    "text": "第123章",
                    "link": "/诗篇/123.md"
                }, {
                    "text": "第124章",
                    "link": "/诗篇/124.md"
                }, {
                    "text": "第125章",
                    "link": "/诗篇/125.md"
                }, {
                    "text": "第126章",
                    "link": "/诗篇/126.md"
                }, {
                    "text": "第127章",
                    "link": "/诗篇/127.md"
                }, {
                    "text": "第128章",
                    "link": "/诗篇/128.md"
                }, {
                    "text": "第129章",
                    "link": "/诗篇/129.md"
                }, {
                    "text": "第13章",
                    "link": "/诗篇/13.md"
                }, {
                    "text": "第130章",
                    "link": "/诗篇/130.md"
                }, {
                    "text": "第131章",
                    "link": "/诗篇/131.md"
                }, {
                    "text": "第132章",
                    "link": "/诗篇/132.md"
                }, {
                    "text": "第133章",
                    "link": "/诗篇/133.md"
                }, {
                    "text": "第134章",
                    "link": "/诗篇/134.md"
                }, {
                    "text": "第135章",
                    "link": "/诗篇/135.md"
                }, {
                    "text": "第136章",
                    "link": "/诗篇/136.md"
                }, {
                    "text": "第137章",
                    "link": "/诗篇/137.md"
                }, {
                    "text": "第138章",
                    "link": "/诗篇/138.md"
                }, {
                    "text": "第139章",
                    "link": "/诗篇/139.md"
                }, {
                    "text": "第14章",
                    "link": "/诗篇/14.md"
                }, {
                    "text": "第140章",
                    "link": "/诗篇/140.md"
                }, {
                    "text": "第141章",
                    "link": "/诗篇/141.md"
                }, {
                    "text": "第142章",
                    "link": "/诗篇/142.md"
                }, {
                    "text": "第143章",
                    "link": "/诗篇/143.md"
                }, {
                    "text": "第144章",
                    "link": "/诗篇/144.md"
                }, {
                    "text": "第145章",
                    "link": "/诗篇/145.md"
                }, {
                    "text": "第146章",
                    "link": "/诗篇/146.md"
                }, {
                    "text": "第147章",
                    "link": "/诗篇/147.md"
                }, {
                    "text": "第148章",
                    "link": "/诗篇/148.md"
                }, {
                    "text": "第149章",
                    "link": "/诗篇/149.md"
                }, {
                    "text": "第15章",
                    "link": "/诗篇/15.md"
                }, {
                    "text": "第150章",
                    "link": "/诗篇/150.md"
                }, {
                    "text": "第16章",
                    "link": "/诗篇/16.md"
                }, {
                    "text": "第17章",
                    "link": "/诗篇/17.md"
                }, {
                    "text": "第18章",
                    "link": "/诗篇/18.md"
                }, {
                    "text": "第19章",
                    "link": "/诗篇/19.md"
                }, {
                    "text": "第2章",
                    "link": "/诗篇/2.md"
                }, {
                    "text": "第20章",
                    "link": "/诗篇/20.md"
                }, {
                    "text": "第21章",
                    "link": "/诗篇/21.md"
                }, {
                    "text": "第22章",
                    "link": "/诗篇/22.md"
                }, {
                    "text": "第23章",
                    "link": "/诗篇/23.md"
                }, {
                    "text": "第24章",
                    "link": "/诗篇/24.md"
                }, {
                    "text": "第25章",
                    "link": "/诗篇/25.md"
                }, {
                    "text": "第26章",
                    "link": "/诗篇/26.md"
                }, {
                    "text": "第27章",
                    "link": "/诗篇/27.md"
                }, {
                    "text": "第28章",
                    "link": "/诗篇/28.md"
                }, {
                    "text": "第29章",
                    "link": "/诗篇/29.md"
                }, {
                    "text": "第3章",
                    "link": "/诗篇/3.md"
                }, {
                    "text": "第30章",
                    "link": "/诗篇/30.md"
                }, {
                    "text": "第31章",
                    "link": "/诗篇/31.md"
                }, {
                    "text": "第32章",
                    "link": "/诗篇/32.md"
                }, {
                    "text": "第33章",
                    "link": "/诗篇/33.md"
                }, {
                    "text": "第34章",
                    "link": "/诗篇/34.md"
                }, {
                    "text": "第35章",
                    "link": "/诗篇/35.md"
                }, {
                    "text": "第36章",
                    "link": "/诗篇/36.md"
                }, {
                    "text": "第37章",
                    "link": "/诗篇/37.md"
                }, {
                    "text": "第38章",
                    "link": "/诗篇/38.md"
                }, {
                    "text": "第39章",
                    "link": "/诗篇/39.md"
                }, {
                    "text": "第4章",
                    "link": "/诗篇/4.md"
                }, {
                    "text": "第40章",
                    "link": "/诗篇/40.md"
                }, {
                    "text": "第41章",
                    "link": "/诗篇/41.md"
                }, {
                    "text": "第42章",
                    "link": "/诗篇/42.md"
                }, {
                    "text": "第43章",
                    "link": "/诗篇/43.md"
                }, {
                    "text": "第44章",
                    "link": "/诗篇/44.md"
                }, {
                    "text": "第45章",
                    "link": "/诗篇/45.md"
                }, {
                    "text": "第46章",
                    "link": "/诗篇/46.md"
                }, {
                    "text": "第47章",
                    "link": "/诗篇/47.md"
                }, {
                    "text": "第48章",
                    "link": "/诗篇/48.md"
                }, {
                    "text": "第49章",
                    "link": "/诗篇/49.md"
                }, {
                    "text": "第5章",
                    "link": "/诗篇/5.md"
                }, {
                    "text": "第50章",
                    "link": "/诗篇/50.md"
                }, {
                    "text": "第51章",
                    "link": "/诗篇/51.md"
                }, {
                    "text": "第52章",
                    "link": "/诗篇/52.md"
                }, {
                    "text": "第53章",
                    "link": "/诗篇/53.md"
                }, {
                    "text": "第54章",
                    "link": "/诗篇/54.md"
                }, {
                    "text": "第55章",
                    "link": "/诗篇/55.md"
                }, {
                    "text": "第56章",
                    "link": "/诗篇/56.md"
                }, {
                    "text": "第57章",
                    "link": "/诗篇/57.md"
                }, {
                    "text": "第58章",
                    "link": "/诗篇/58.md"
                }, {
                    "text": "第59章",
                    "link": "/诗篇/59.md"
                }, {
                    "text": "第6章",
                    "link": "/诗篇/6.md"
                }, {
                    "text": "第60章",
                    "link": "/诗篇/60.md"
                }, {
                    "text": "第61章",
                    "link": "/诗篇/61.md"
                }, {
                    "text": "第62章",
                    "link": "/诗篇/62.md"
                }, {
                    "text": "第63章",
                    "link": "/诗篇/63.md"
                }, {
                    "text": "第64章",
                    "link": "/诗篇/64.md"
                }, {
                    "text": "第65章",
                    "link": "/诗篇/65.md"
                }, {
                    "text": "第66章",
                    "link": "/诗篇/66.md"
                }, {
                    "text": "第67章",
                    "link": "/诗篇/67.md"
                }, {
                    "text": "第68章",
                    "link": "/诗篇/68.md"
                }, {
                    "text": "第69章",
                    "link": "/诗篇/69.md"
                }, {
                    "text": "第7章",
                    "link": "/诗篇/7.md"
                }, {
                    "text": "第70章",
                    "link": "/诗篇/70.md"
                }, {
                    "text": "第71章",
                    "link": "/诗篇/71.md"
                }, {
                    "text": "第72章",
                    "link": "/诗篇/72.md"
                }, {
                    "text": "第73章",
                    "link": "/诗篇/73.md"
                }, {
                    "text": "第74章",
                    "link": "/诗篇/74.md"
                }, {
                    "text": "第75章",
                    "link": "/诗篇/75.md"
                }, {
                    "text": "第76章",
                    "link": "/诗篇/76.md"
                }, {
                    "text": "第77章",
                    "link": "/诗篇/77.md"
                }, {
                    "text": "第78章",
                    "link": "/诗篇/78.md"
                }, {
                    "text": "第79章",
                    "link": "/诗篇/79.md"
                }, {
                    "text": "第8章",
                    "link": "/诗篇/8.md"
                }, {
                    "text": "第80章",
                    "link": "/诗篇/80.md"
                }, {
                    "text": "第81章",
                    "link": "/诗篇/81.md"
                }, {
                    "text": "第82章",
                    "link": "/诗篇/82.md"
                }, {
                    "text": "第83章",
                    "link": "/诗篇/83.md"
                }, {
                    "text": "第84章",
                    "link": "/诗篇/84.md"
                }, {
                    "text": "第85章",
                    "link": "/诗篇/85.md"
                }, {
                    "text": "第86章",
                    "link": "/诗篇/86.md"
                }, {
                    "text": "第87章",
                    "link": "/诗篇/87.md"
                }, {
                    "text": "第88章",
                    "link": "/诗篇/88.md"
                }, {
                    "text": "第89章",
                    "link": "/诗篇/89.md"
                }, {
                    "text": "第9章",
                    "link": "/诗篇/9.md"
                }, {
                    "text": "第90章",
                    "link": "/诗篇/90.md"
                }, {
                    "text": "第91章",
                    "link": "/诗篇/91.md"
                }, {
                    "text": "第92章",
                    "link": "/诗篇/92.md"
                }, {
                    "text": "第93章",
                    "link": "/诗篇/93.md"
                }, {
                    "text": "第94章",
                    "link": "/诗篇/94.md"
                }, {
                    "text": "第95章",
                    "link": "/诗篇/95.md"
                }, {
                    "text": "第96章",
                    "link": "/诗篇/96.md"
                }, {
                    "text": "第97章",
                    "link": "/诗篇/97.md"
                }, {
                    "text": "第98章",
                    "link": "/诗篇/98.md"
                }, {
                    "text": "第99章",
                    "link": "/诗篇/99.md"
                }]
            }, {
                "text": "路得记",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/路得记/1.md"
                }, {
                    "text": "第2章",
                    "link": "/路得记/2.md"
                }, {
                    "text": "第3章",
                    "link": "/路得记/3.md"
                }, {
                    "text": "第4章",
                    "link": "/路得记/4.md"
                }]
            }, {
                "text": "那鸿书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/那鸿书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/那鸿书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/那鸿书/3.md"
                }]
            }, {
                "text": "阿摩司书",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/阿摩司书/1.md"
                }, {
                    "text": "第2章",
                    "link": "/阿摩司书/2.md"
                }, {
                    "text": "第3章",
                    "link": "/阿摩司书/3.md"
                }, {
                    "text": "第4章",
                    "link": "/阿摩司书/4.md"
                }, {
                    "text": "第5章",
                    "link": "/阿摩司书/5.md"
                }, {
                    "text": "第6章",
                    "link": "/阿摩司书/6.md"
                }, {
                    "text": "第7章",
                    "link": "/阿摩司书/7.md"
                }, {
                    "text": "第8章",
                    "link": "/阿摩司书/8.md"
                }, {
                    "text": "第9章",
                    "link": "/阿摩司书/9.md"
                }]
            }, {
                "text": "雅歌",
                "collapsible": true,
                "items": [{
                    "text": "第1章",
                    "link": "/雅歌/1.md"
                }, {
                    "text": "第2章",
                    "link": "/雅歌/2.md"
                }, {
                    "text": "第3章",
                    "link": "/雅歌/3.md"
                }, {
                    "text": "第4章",
                    "link": "/雅歌/4.md"
                }, {
                    "text": "第5章",
                    "link": "/雅歌/5.md"
                }, {
                    "text": "第6章",
                    "link": "/雅歌/6.md"
                }, {
                    "text": "第7章",
                    "link": "/雅歌/7.md"
                }, {
                    "text": "第8章",
                    "link": "/雅歌/8.md"
                }]
            }]
        }],
        outline: 2,
        outlineTitle: "大纲",
        socialLinks: [{
            icon: "github",
            link: "https://github.com/Lisk809/Lisk"
        }],
        footer: {
            message: '<a href="https://github.com/Lisk809/bible">the Project</a>使用 <a href="https://github.com/KiviBotLab/docs/blob/main/LICENSE">MIT</a> 协议开放源代码\nPower by <a href="https://vitepress.docschina.org/">VitePress</a><br>Made with Love❤️and confidence.',
            copyright: 'Copyright © 2022-PRESENT <a href="https://github.com/Lisk809">Lisk</a>',
        },
        lastUpdatedText: "上次更新",
        docFooter: {
            prev: "上一页",
            next: "下一页",
        },
        editLink: {
            pattern: "https://github.com/Lisk809/bible/edit/main/src/docs/:path",
            text: "在 GitHub 上编辑",
        },
    },
});